- name: disable nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs 20
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - mysql

- name: create expense user
  ansible.builtin.user:
    name: expense

- name: include from common role 
  include_role: 
    name: common 
    tasks_from: main 

# - name: create app directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: Download the application code to created app directory
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: unzip the application code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: copy SystemD backend Service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: daemon-reload of the service
  ansible.builtin.systemd_service:
    enabled: true
    state: restarted
    daemon_reload: true
    name: backend

- name: install python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - cryptography
    - PyMySQL

- name: import mysql data
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ mysql_host }}"

- name: restart the service
  ansible.builtin.service:
    name: backend
    state: restarted
