---
- name: Install mysql 
  hosts: mysql 
  become: yes
  tasks: 
  - name: Install mysql libraries 
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography
    
  - name: install mysql-server 
    ansible.builtin.dnf: 
      name: mysql-server 
      state: installed 
    
  - name: start mysql and enable 
    ansible.builtin.service: 
      name: mysqld
      state: started 
      enabled: yes 

  - name: connect to mysql server 
    community.mysql.mysql_info:
      login_user: root 
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.tridev.online
    register: mysql_info
    ignore_errors: true
  
  - name: print the output for the mysql login info 
    ansible.builtin.debug: 
      msg: "MySQL info: {{ mysql_info }}"

  - name: setup the mysql password 
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true 
