$ANSIBLE_VAULT;1.1;AES256
34626164663239613634333262653464663264633931343137363032356232663238366130356135
3730663430343865666461383439623864326532626539340a646633376532333631383230643463
63326331666538306330393538393362326164316265313135643139626531643066363430626635
3363396536373764640a623266663064303134633964393630633861383236323936663139633438
61316534383438323766633764303763396230303662623430366436336330366164373763633461
3535656232306633363235316137333437373332626564323233
